#!/bin/bash
# AORR - Simple Image Optimization Guide
# The optimization tools (ImageMagick and WebP) are not installed on this system

echo "📋 Image Optimization Task List"
echo "================================================"
echo ""
echo "⚠️  Image optimization tools are not installed on this system."
echo ""
echo "To optimize images, you can either:"
echo ""
echo "OPTION 1: Install tools on your server (Linux)"
echo "   sudo apt-get update"
echo "   sudo apt-get install imagemagick webp"
echo "   Then run: ./optimize-images.sh"
echo ""
echo "OPTION 2: Use online tools (Easiest)"
echo "   • Squoosh.app - https://squoosh.app (Free, best quality)"
echo "   • TinyPNG - https://tinypng.com (Free, batch upload)"
echo "   • CloudConvert - https://cloudconvert.com (Batch WebP conversion)"
echo ""
echo "OPTION 3: Use Node.js (if available)"
echo "   npm install -g sharp-cli"
echo "   sharp -i images/*.jpg -o images/ -f webp -q 80"
echo ""
echo "📊 PRIORITY IMAGES TO OPTIMIZE (Largest files):"
echo "================================================"
cd images 2>/dev/null || exit
du -h *.jpg *.png 2>/dev/null | sort -hr | head -10
echo ""
echo "🎯 TARGET: Each image should be under 200KB"
echo "   Hero images: < 150KB"
echo "   Content images: < 100KB"
echo "   Icons/thumbnails: < 30KB"
echo ""
echo "📝 Remember to:"
echo "   1. Create WebP versions of all images"
echo "   2. Create responsive sizes (480w, 768w, 1200w)"
echo "   3. Keep JPG fallbacks for older browsers"
echo "   4. Update HTML to use <picture> tags"
